[project]
name = "celia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alan Paredes", email = "alan.paredes@uni.lu" }
]
requires-python = ">=3.12.10"
dependencies = [
    "certifai",
    "dice-ml",
    "fastjsonschema==2.21.1",
    "jsonschema==4.23.0",
    "matplotlib==3.10.1",
    "notebook>=7.4.2",
    "pandas==2.2.3",
    "raiutils==0.4.2",
    "scikit-learn==1.3.2",
    "seaborn>=0.13.2",
    "torch==2.6.0",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "category-encoders>=2.7.0",
    "pytest>=8.3.5",
    "xgboost>=3.0.1",
]

[tool.uv.sources]
certifai = { git = "https://github.com/alanpar97/CERTIFAI.git" }
dice-ml = { git = "https://github.com/alanpar97/DiCE.git" }
