from abc import ABC, abstractmethod
from typing import Union, Optional, List, Tuple, Any
from celia.model import BaseModel
from celia.data import BaseData, PublicData
import pandas as pd
import numpy as np

class BaseExplainer(ABC):
    """
    Abstract base class for explainers in Celia.
    All explainer classes should inherit from this class and implement the required methods.
    """

    def __init__(self, model: BaseModel, data: BaseData, *args, **kwargs):
        """
        Initialize the BaseExplainer with a model instance.

        Parameters
        ----------
        model : BaseModel
            The model instance to be explained.
        data : BaseData
            The data instance associated with the model.

        """
        self._model = model
        self._data = data
        self._explainer = self._create_explainer(self.model, self.data, *args, **kwargs)

    @property
    def model(self) -> BaseModel:
        """
        Return the model associated with this explainer.

        Returns
        -------
        BaseModel
            The model instance used by the explainer.
        """
        return self._model

    @property
    def data(self) -> BaseData:
        """
        Return the data associated with this explainer.

        Returns
        -------
        BaseData
            The data instance used by the explainer.
        """
        return self._data

    @property
    def explainer(self) -> Any:
        """
        Return the explainer instance created by the subclass.

        Returns
        -------
        Any
            The explainer instance initialized by the subclass.
        """
        return self._explainer

    @abstractmethod
    def _create_explainer(self, model: BaseModel, data:BaseData, *args, **kwargs) -> Any:
        """
        Create the explainer instance.

        This method should be implemented by subclasses to initialize the explainer
        with the necessary parameters and configurations.
        """
        raise NotImplementedError("Subclasses must implement _create_explainer method.")

    @abstractmethod
    def generate_counterfactuals(self, sample: Union[pd.DataFrame, pd.Series], *args, **kwargs) -> pd.DataFrame:
        """
        Generate counterfactual explanations for the given data.

        Parameters
        ----------
        sample : Union[pd.DataFrame, pd.Series]
            The data to generate explanations for.

        Returns
        -------
        pd.DataFrame
            Counterfactuals generated by the explainer.
        """
        raise NotImplementedError("Subclasses must implement generate_counterfactuals method.")

    def validate_sample(self, sample: Union[pd.DataFrame, pd.Series], *args, **kwargs) -> None:
        """
        Validate the input sample for generating counterfactuals.

        This method checks that the sample is of the correct type and contains the required columns.
        It then calls the subclass-specific `_validate_sample` method to enforce any additional constraints.

        Parameters
        ----------
        sample : Union[pd.DataFrame, pd.Series]
            The data to validate.

        Raises
        ------
        ValueError
            If the sample does not match the expected format or features.
        TypeError
            If the sample is not a pandas DataFrame or Series.
        """
        self.validate_sample_dtypes(sample, *args, **kwargs)
        if isinstance(sample, (pd.DataFrame, pd.Series)):
            self._validate_sample_columns_presence(sample)
        self._validate_sample(sample, *args, **kwargs)

    @abstractmethod
    def _validate_sample(self, sample: Union[pd.DataFrame, pd.Series], *args, **kwargs) -> None:
        """
        Subclass-specific validation of the input sample for counterfactual generation.

        This method is called after generic checks (type validation and column presence)
         have already been performed in `validate_sample`.

        Subclasses should implement this method to enforce any additional constraints
        specific to the counterfactual generation logic (e.g., task-specific assumptions,
        preprocessing requirements, or format constraints).

        Parameters
        ----------
        sample : Union[pd.DataFrame, pd.Series]
            The input data instance(s) to validate. Guaranteed to be of valid type and
            contain all required features.

        Raises
        ------
        ValueError
            If the sample violates subclass-specific requirements.
        """
        pass

    def validate_sample_dtypes(self, sample: Union[pd.DataFrame, pd.Series], *args, **kwargs) -> None:
        """
        Validate the type of the input sample.

        Parameters
        ----------
        sample : Union[pd.DataFrame, pd.Series]
            The data to validate.

        Raises
        ------
        TypeError
            If the sample is not a pandas DataFrame or Series.
        """
        if not isinstance(sample, (pd.DataFrame, pd.Series)):
            raise TypeError(f"Sample must be a pandas DataFrame or Series, got {type(sample).__name__}")

    def _validate_input_types(self, *args, **kwargs) -> None:
        """
        Subclass-specific validation of the input types.

        This method is called after generic type validation in `validate_input_types`.
        Subclasses should implement this method to enforce any additional type constraints
        specific to the counterfactual generation logic.

        Parameters
        ----------
        sample : Union[pd.DataFrame, pd.Series]
            The input data instance(s) to validate. Guaranteed to be of valid type.

        Raises
        ------
        ValueError
            If the sample violates subclass-specific type requirements.
        """
        pass

    def _validate_sample_columns_presence(self, sample: Union[pd.DataFrame, pd.Series]) -> None:
        """
        Check if the sample contains the required columns.

        Parameters
        ----------
        sample : Union[pd.DataFrame, pd.Series]
            The data to check.

        Raises
        ------
        ValueError
            If the sample does not contain the columns defined in self.data.
        """

        if isinstance(self.data, PublicData):
            required_columns = self.data.column_names
        else:
            raise ValueError(f"Data must be an instance of PublicData, got {type(self.data)}")

        if isinstance(sample, pd.Series):
            sample_columns = list(sample.index)
        else:
            sample_columns = list(sample.columns)

        #Lowercase everything for case-insensitive matching
        sample_lower = [c.lower() for c in sample_columns]
        required_lower = [c.lower() for c in required_columns]

        # Duplicate check of sample columns
        if len(sample_lower) != len(set(sample_lower)):
            dupes = {c for c in sample_lower if sample_lower.count(c) > 1}
            raise ValueError(f"Duplicate column names in sample: {sorted(dupes)}")

        sample_columns_set = set(sample_columns)
        required_columns_set = set(required_columns)
        if sample_columns_set != required_columns_set:
            missing = required_columns_set - sample_columns_set
            extra = sample_columns_set - required_columns_set
            msg = []
            if missing:
                msg.append(f"Missing columns: {sorted(missing)}")
            if extra:
                msg.append(f"Unexpected columns: {sorted(extra)}")
            raise ValueError("Sample column mismatch. " + " ".join(msg))

    '''
    def _check_feasible_ranges(self, sample: Union[pd.DataFrame, pd.Series]) -> None:
        """
        Validates that all sample feature values are within the feasible values defined in self.data.

        Parameters
        ----------
        sample : Union[pd.DataFrame, pd.Series]
            One or more samples to validate.

        Raises
        ------
        ValueError
            If any feature value violates its feasibility constraints.
        """
        feasible = self.data.feasible_values

        # Normalize to DataFrame
        if isinstance(sample, pd.Series):
            sample = sample.to_frame().T

        for idx, row in sample.iterrows():
            for feature, value in row.items():
                if feature not in feasible:
                    continue  # No constraint for this feature

                constraint = feasible[str(feature)]

                #Continuous constraints
                if isinstance(constraint, tuple) and len(constraint) == 2:
                    min_val, max_val = constraint
                    if not (min_val <= value <= max_val):
                        raise ValueError(
                            f"Sample {idx}: Feature '{feature}' = {value} is out of range [{min_val}, {max_val}]"
                        )
                # Categorical constraints
                else:
                    if value not in constraint:
                        raise ValueError(
                            f"Sample {idx}: Feature '{feature}' = {value} is not in allowed set {constraint}"
                        )
        '''

class RegressorExplainer(BaseExplainer):
    """
    Base class for explainers that work with regression models.
    Inherits from BaseExplainer and implements additional validation for regression-specific requirements.
    """

    def __init__(self, model: BaseModel, data: BaseData, *args, **kwargs):
        super().__init__(model, data, *args, **kwargs)
        #TODO: Uncomment when task_type is implemented in BaseModel

        ''' Validate that the model is a regression model.
        if self.model.task_type != 'regression':
            raise ValueError("RegressorExplainer can only be used with regression task.")
        '''


    def generate_counterfactuals(self, sample: Union[pd.DataFrame, pd.Series],
                                 target_range: Union[List[float], Tuple[float, float]] = None,
                                 *args, **kwargs) -> pd.DataFrame:
        """
        Generate counterfactual explanations for the given input sample.

        This is the public interface for counterfactual generation in regression explainers.
        It performs input validation (e.g., validate target ranges), and delegates the actual generation logic
        to the subclass-specific `_generate_counterfactuals` method.

        Parameters
        ----------
        sample : Union[pd.DataFrame, pd.Series]
            A single instance or multiple instances for which counterfactual explanations are to be generated.

        target_range : Union[List[float], Tuple[float, float]], optional
            A desired output range (min, max) that counterfactual predictions should aim to fall within.

        Returns
        -------
        pd.DataFrame
            A DataFrame containing one or more counterfactual samples.
        """
        super().validate_sample(sample)
        self._validate_target_range(target_range)
        filtered_samples = self._filter_samples_within_target_range(sample, target_range)
        if filtered_samples.empty:
            raise ValueError("No samples outside the target range. Cannot generate counterfactuals.")
        return self._generate_counterfactuals(sample=filtered_samples,
                                              target_range=target_range,
                                              *args,
                                              **kwargs)

    @staticmethod
    def _validate_target_range(target_range: Union[List[float], Tuple[float, float]]) -> None:
        """
        Validate the target range for regression counterfactuals.

        Parameters
        ----------
        target_range : Union[List[float], Tuple[float, float]]
            The desired output range for counterfactuals.

        Raises
        ------
        ValueError
            If the target range is invalid (e.g., min >= max).
        """
        if target_range is None:
            raise ValueError("target_range must be provided for regression counterfactual generation.")
        if not isinstance(target_range, (list, tuple)) or len(target_range) != 2:
            raise ValueError("target_range must be a list or tuple of two elements [min, max].")
        if target_range[0] >= target_range[1]:
            raise ValueError(f"Invalid target range: {target_range}. Min must be less than max.")

    def _filter_samples_within_target_range(self, sample: Union[pd.DataFrame, pd.Series],
                                            target_range: Union[List[float], Tuple[float, float]]) -> pd.DataFrame:
        """
        Filter out samples whose predictions already fall within the desired target range.

        This method is used in regression-based counterfactual generation to exclude instances
        that already satisfy the desired output condition. A message is printed for excluded
        samples, including their indices.

        Parameters
        ----------
        sample : Union[pd.DataFrame, pd.Series]
            The input sample(s) for which counterfactuals are to be generated.
            Can be a single-row Series or a multi-row DataFrame.

        target_range : Union[List[float], Tuple[float, float]]
            A (min, max) tuple indicating the desired prediction output range.

        Returns
        -------
        pd.DataFrame
            A filtered DataFrame containing only those samples whose predictions fall
            outside the target range.
        """
        if isinstance(sample, pd.Series):
            sample = sample.to_frame().T

        preds = self.model.predict(sample)
        min_val, max_val = target_range

        out_of_range_mask = (preds < min_val) | (preds > max_val)
        filtered_sample = sample[out_of_range_mask]

        if not filtered_sample.empty and filtered_sample.shape[0] < sample.shape[0]:
            excluded_indices = sample[~out_of_range_mask].index.tolist()
            print(
                f"[Warning] Excluded {len(excluded_indices)} sample(s) already within target range: {excluded_indices}")

        return filtered_sample

    def _validate_sample(self, sample: Union[pd.DataFrame, pd.Series],
                         target_range: Union[List[float], Tuple[float, float]] = None, *args, **kwargs) -> None:
        pass

    @abstractmethod
    def _generate_counterfactuals(self, sample: Union[pd.DataFrame, pd.Series],
                                  target_range: Union[List[float], Tuple[float, float]],
                                  *args, **kwargs) -> pd.DataFrame:
        """
        Abstract method to be implemented by subclasses to generate counterfactuals.

        Assumes that `sample` and `target_range` have already been validated by the public method.
        Subclasses must implement this method to define their specific counterfactual generation logic.

        Parameters
        ----------
        sample : Union[pd.DataFrame, pd.Series]
            A validated single instance to generate counterfactuals for.

        target_range : Union[List[float], Tuple[float, float]]
            A validated (min, max) target range for the regression output.

        Returns
        -------
        pd.DataFrame
            A DataFrame containing counterfactual instances corresponding to the input.
        """

